### ISSUE TITLE
Incorrect explanation in Overview

### ISSUE THREAD

**Issue by concentrateddon** [MicrosoftDocs/quantum-docs-pr#1004]
The document states, "Where classical computers use familiar silicon-based chips, quantum computers use quantum materials such as atoms, ions, photons, or electrons.." 

(https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/overview/understanding-quantum-computing.md)

"Classical" is probably not the right word; you probably mean "classic." 

But more importantly, "classic" computers do indeed use atoms (it's what everything is constructed from) and electrons (which are what comprises the electricity that processors use). "Classic" (e.g., binary) processors have also been created which use photons (light). The type of particle used is not what differentiates quantum computing. The comparison/differentiation here doesn't really work.

It might more more accurate to say that "Where classic computer processors use a system of binary math, where each bit of information is either a 1 or a 0, quantum computers recognize a different and non-binary set of states." That's really the differentiation — how they compute, more so than the materials they use to compute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b6abb91-3dfa-b4cb-9bea-f656bf629f4c
* Version Independent ID: 8f4efb38-0429-7be1-9d25-8e5faed24195
* Content: [Understanding quantum computing - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/overview/understanding-quantum-computing)
* Content Source: [articles/overview/understanding-quantum-computing.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/overview/understanding-quantum-computing.md)
* Product: **quantum**
* GitHub Login: @Bradben
* Microsoft Alias: **bradben**

**Comment by Rishit-dagli** [comment]
@concentrateddon This seems to me like a great addition maybe we could have something like this-

Where classic computers use familiar silicon-based chips, quantum computers use qubits that represent materials such as atoms, ions, photons, or electrons and use their quantum properties.

**Comment by geduardo** [comment]
Thank you @concentrateddon and @Rishit-dagli for your contributions!

Regarding the question "classic" vs "classical", the standard term is "classical", meaning that "classical computers" use a classical computation model that has been used for a long time, and not that are typical computers. Similarly, we say "classical physics" and not "classic physics", which is also in part why we say "classical computers", since they are based on the laws of classical physics. As @concentrateddon points, it's true that some components of modern classical computers exploit quantum phenomena to implement logic gates, e.g, the transistor. However, those gates form a model of computation that can be also implemented with classical physics only (e.g. of logic gates with marbles and wooden tracks: https://www.youtube.com/watch?v=yhGwtfOyN2c&t=20s) and are thus classical computers despite the fact they use quantum mechanics to work.

But it's true that the current statement is not precise enough. What about this (rephrasing what @Rishit-dagli said):

> Where classical computers use familiar silicon-based chips, quantum computers use quantum systems such as atoms, ions, photons, or electrons. They use their quantum properties to represent bits that can be prepared in different quantum superpositions of 1 and 0.

**Comment by Rishit-dagli** [comment]
> Thank you @concentrateddon and @Rishit-dagli for your contributions!
> 
> Regarding the question "classic" vs "classical", the standard term is "classical", meaning that "classical computers" use a classical computation model that has been used for a long time, and not that are typical computers. Similarly, we say "classical physics" and not "classic physics", which is also in part why we say "classical computers", since they are based on the laws of classical physics. As @concentrateddon points, it's true that some components of modern classical computers exploit quantum phenomena to implement logic gates, e.g, the transistor. However, those gates form a model of computation that can be also implemented with classical physics only (e.g. of logic gates with marbles and wooden tracks: https://www.youtube.com/watch?v=yhGwtfOyN2c&t=20s) and are thus classical computers despite the fact they use quantum mechanics to work.
> 
> But it's true that the current statement is not precise enough. What about this (rephrasing what @Rishit-dagli said):
> 
> > Where classical computers use familiar silicon-based chips, quantum computers use quantum systems such as atoms, ions, photons, or electrons. They use their quantum properties to represent bits that can be prepared in different quantum superpositions of 1 and 0.

This seems to me like a better way of putting the statement.

**Comment by geduardo** [comment]
Closing since it was solved.
