### ISSUE TITLE
What implementation of LaTex markdown is used for the math in documentation?

### ISSUE THREAD

**Issue by lwoodyiii** [MicrosoftDocs/quantum-docs-pr#347]
This would be helpful when contributing to ensure that our markdown will render correctly when "built". Thanks!

**Comment by lwoodyiii** [comment]
Is it [https://upmath.me/](https://upmath.me/) possibly?

**Comment by tcNickolas** [comment]
We use MathJax 2.7.2 to render the output of the OPS build, which is in turn produced by DocFX using Markdig. 

This combination of tools is known to sometimes produce weird and unexpected results. For example, we have to use `\\\\` instead of `\\` to mark new line of table elements because half of the backslashes are interpreted as escape characters. Another example is that sometimes the formulas with sums in them will not render if subscript of `\sum` is given after the superscript.

Our CI on this repository renders the contents of pull requests, so we can preview them before merging.  For my work, I typically create a branch and preview the changes on it even before opening a PR (that's the only way I was able to verify that the changes in https://github.com/Microsoft/QuantumLibraries/pull/24 make sense!), but you'd need write access to the repo for that.

**Comment by cgranade** [comment]
Closing, as this question has been answered. Thanks for the feedback!
