### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by jpetitte** [MicrosoftDocs/quantum-docs-pr#451]
I think there is some confusion with variables. 

If the following is accepted as true: 
 - A matrix of size m×n is a collection of mn complex numbers

Then shouldn't this: 
- Note that a vector of dimension n is simply a matrix of size n×1. 
Actually be: 
- Note that a vector of dimension m is simply a matrix of size m×1. 

As "m" denotes row, and "n" denotes column, and vectors have a single column, but can vary in rows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 434e640f-ea90-3c49-9510-1fda8cbee7a1
* Version Independent ID: 9c5af71d-7980-d644-b2bc-9b54bda5e551
* Content: [Vectors and matrices](https://docs.microsoft.com/en-us/quantum/concepts/vectors-and-matrices?view=qsharp-preview#feedback)
* Content Source: [articles/concepts/vectors-and-matrices.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/concepts/vectors-and-matrices.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by geduardo** [comment]
The common notation to denote rows and columns is the order in in the product a×b rather than the letters themselves, denoting with the left integer the number of rows and with the right integer the number of columns, eg. a matrix 2×3 has 2 rows and 3 columns. 

In Quantum Mechanics the standard convention is to denote states by column vectors of the dimension of the Hilbert space of the system. For example, in a qubit (where the Hilbert space has dimension 2) the state |1> is represented by the vector column vector (0,1)T, which is a matrix of size 2x1. That's why the notation introduces the vectors as n×1 matrices, where n usually is the dimension of the Hilbert space.

On the other hand, another convention in QM is that operators acts on the states from the left, transforming an initial state into another state that lives in the same Hilbert space or not. Typically, this transformation is represented by a matrix multiplication of a matrix of size m×n (where m is the dimension of the Hilbert space of the output state and n is the dimension of the Hilbert state of the initial state) and the matrix of size n×1 representing the initial state. The result of the multiplication is an m×1 vector that represents the transformed state. A good mnemotechnical rule to keep track of the dimensions in a matrix multiplication is that the internal indices must be the same and cancel each other and the final product is the dimension of the remaining dimensions, eg. (m×n)•(n×s)=(m×s). For more information on matrix multiplication: https://en.wikipedia.org/wiki/Matrix_multiplication

I guess that's the reason why the author chose that configuration of letters to design indices. Although it can be a bit weird for newcomers, it is very useful to keep track of the dimensions of each state.
