### ISSUE TITLE
No-install getting started link

### ISSUE THREAD

**Issue by bettinaheim** [MicrosoftDocs/quantum-docs-pr#518]
Doing some prep for a summer school, Inoticed that I think it would be nice to give [this link](https://mybinder.org/v2/gh/Microsoft/Quantum/master?filepath=Samples%2Fsrc%2FIntroToIQSharp%2FNotebook.ipynb) some consideration. It is basically the first place where we send people, and having followed it, I was really missing a "and now do that" kind of continuation/link in the opened notebook that would gently lead a newby towards doing something with it without having a concrete idea in mind of what to code. I'd suggest to link to the [katas index](https://mybinder.org/v2/gh/Microsoft/QuantumKatas/master?filepath=index.ipynb)?

**Comment by KittyYeungQ** [comment]
Hi @bettinaheim the first link no longer loads. Would this be considered as a resolved issue we should close?

**Comment by cgranade** [comment]
The links that @bettinaheim provided can be adapted using the `filepath` query parameter to mybinder.org to point to the newest location of each notebook. For instance, the first link points the new BinderHub session to `Samples/src/IntroToIQSharp/Notebook.ipynb`, which has since moved to `samples/getting-started/intro-to-iqsharp/Notebook.ipynb`, such that the URL can be adapted to `https://mybinder.org/v2/gh/Microsoft/Quantum/master?filepath=samples%2Fgetting-started%2Fintro-to-iqsharp%2FNotebook.ipynb`.

**Comment by KittyYeungQ** [comment]
This kind of experience will be integrated to the new learning platform.
