### ISSUE TITLE
Compilation error in the Callable Expression sample

### ISSUE THREAD

**Issue by tanaka-takayoshi** [MicrosoftDocs/quantum-docs-pr#614]
To confirm the following code example,

```
let combinedOp = Func<(Qubit[] => Unit), (Qubit[] => Unit is Adj)>(Op1, Op2, Op3);
```

I wrote the following code but it has compilation error.

```
function Func<'T1, 'T2>(op1: 'T1, op2: 'T2, op3: 'T1): 'T2 {
	return op2;
}

function Op1(qubits: Qubit[]): Unit is Adj {
	
}

function Op2(qubits: Qubit[]): Unit is Adj {
	
}

function Op3(qubits: Qubit[]): Unit {
	
}

function CallableExample(): Unit {
	let combinedOp = Func<(Qubit[] => Unit), (Qubit[] => Unit is Adj)>(Op1, Op2, Op3);
}
```

The errors are:
```
Error	QS6210	The type of the given argument does not match the expected type. Got an argument of type (Qubit[] -> Unit), expecting one of type (Qubit[] => Unit) instead.		
Error	QS6210	The type of the given argument does not match the expected type. Got an argument of type (Qubit[] -> Unit), expecting one of type (Qubit[] => Unit is Adj) instead.	
Error	QS6210	The type of the given argument does not match the expected type. Got an argument of type (Qubit[] -> Unit), expecting one of type (Qubit[] => Unit) instead.			
```

Is it my mistake or is there any unexpected behavior in Q# compiler?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0386e920-3c2b-81a6-f32c-12653d2b0321
* Version Independent ID: 854cd620-b8ec-270b-8d55-34952a234016
* Content: [Expressions - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/language/expressions?view=qsharp-preview#copy-and-update-expressions)
* Content Source: [articles/language/expressions.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/language/expressions.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **Alan.Geller@microsoft.com**

**Comment by gillenhaalb** [comment]
@tanaka-takayoshi Apologies for the late response! I think the error is simply due to the operation definitions in your code example: replacing the `function` tags with `operation` should take care of it.

This is hinted at in the error messages, because functions have the signature using `->`, whereas operations use `=>`. In this case they would have to be operations, because they are taking qubits as an argument. More details can be found on the [type model page](https://docs.microsoft.com/en-us/quantum/language/type-model?view=qsharp-preview#operation-and-function-types).
