### ISSUE TITLE
 quantum-docs-pr/articles/quickstarts/qrng.md 

### ISSUE THREAD

**Issue by andrewenoble** [MicrosoftDocs/quantum-docs-pr#680]
Enjoying working through this material.  I had to make a couple changes.

Q# operation code:
Changed "let r = M(v);" to "let r = M(qubit);"

C# host program:
Changed "SampleQuantumRandomNumberGenerator" to "QuantumRandomNumberGenerator"
(to match the identifier in the operation code)

**Comment by geduardo** [comment]
Oh, good catch! Thank you very much! To stick with the [Q# Official Style Guide](https://docs.microsoft.com/en-us/quantum/contributing/style-guide?view=qsharp-preview&tabs=guidance) the change should be done the opposite way and change the Q# code to show "SampleQuantumRandomNumberGenerator". This is because, for clarity, operations should be designed with verbs.
I'll create a PR to fix this!

**Comment by geduardo** [comment]
This should be fixed in #682

**Comment by andrewenoble** [comment]
Great!  Good to know.  Thank you!
