### ISSUE TITLE
Possible typo in "Concepts -> Multiple Qubits -> Measuring Two-Qubit States"

### ISSUE THREAD

**Issue by jagandecapri** [MicrosoftDocs/quantum-docs-pr#725]
Hi,

The term e3 seems to be repeated between the first and second qubits at the documentation at [Concepts -> Multiple Qubits -> Measuring Two-Qubit States](https://github.com/MicrosoftDocs/quantum-docs-pr/commit/c80adb52e45682ba62e3ee787c571ff929a77b4d). I'm not sure whether it is supposed to be as such.

> ...if we are interested in measuring the first qubit then S would consist of e2≡10 and e3≡11. Similarly, if we are interested in the second qubit S would consist of e1≡01 and e3≡11

**Comment by cgranade** [comment]
I believe the article is correct as written, in that it uses the notation 𝑒ₖ to refer to the computational basis state labeled by the bitstring representing the integer 𝑘 in big-endian notation. Since `3 == 0b11`, 𝑒₃ = |11⟩. Similarly, since `2 == 0b10` (again in big-endian), 𝑒₂ = |10⟩ in that article's notation. These are the two two-qubit states in which the first qubit is in the 1 state, and so the projector |11⟩⟨11| + |10⟩⟨10| = 𝑒₃𝑒₃⁺ + 𝑒₂𝑒₂⁺ represents a measurement as to whether the first qubit is in the 1 state, written as the Q# partial application `Measure([PauliZ, PauliI], _)`.

**Comment by jagandecapri** [comment]
Thank you for the clarification @cgranade. I'll close this issue. =)

**Comment by cgranade** [comment]
No worries, happy to help, @jagandecapri!
