### ISSUE TITLE
没有中文版

### ISSUE THREAD

**Issue by rexislijunyi** [MicrosoftDocs/quantum-docs-pr#750]
没有中文版，阅读不方便

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 434e640f-ea90-3c49-9510-1fda8cbee7a1
* Version Independent ID: 9c5af71d-7980-d644-b2bc-9b54bda5e551
* Content: [Vectors and matrices in quantum computing - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/concepts/vectors-and-matrices#feedback)
* Content Source: [articles/concepts/vectors-and-matrices.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/concepts/vectors-and-matrices.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **nawiebe@microsoft.com**

**Comment by gillenhaalb** [comment]
Thanks for submitting the feedback! My apologies for having to resort to Google Translate, but the translation came out as "No Chinese version, not easy (/inconvenient) to read". From that, I can guess that you bumped into one of two issues:

1) you've found yourself on the English page specifically (the more likely scenario, seeing as the issue was added via the `en-us` page URL). In this case, you can change to a Chinese version by either:
    - scrolling to the bottom of the page, clicking the globe icon 🌐 where it says "English (United States)", and selecting the new language
    - simply changing the `en-us` in the URL to `zh-cn`, `zh-tw`, or `zh-hk` ("simplified", "traditional", "Hong Kong").

2) the issue is in some of the LaTeX rendering of matrices and math symbols on the page. Unfortunately this is an issue that we've seen on other non-English pages as well, and is not something our US docs team is able to currently take on. However, you could then submit the issue to the GitHub repo for the Chinese page: https://github.com/MicrosoftDocs/quantum-docs-pr.zh-CN/issues.

I apologize again for any inconvenience (or potential mis-translation) if you have to send all this through a translator as I did, but I hope I was able to help! Thanks again for the feedback, and we hope your time with Q# is off to a good start!
