### ISSUE TITLE
Visual Studio Code can't use provided dev container

### ISSUE THREAD

**Issue by samarsha** [MicrosoftDocs/quantum-docs-pr#764]
The repo includes a file .devcontainer/devcontainer.json that Visual Studio Code recognizes, and it offers to reopen the project in a container. However, trying to do that gives this error:

![image](https://user-images.githubusercontent.com/33814365/77363465-017b8d00-6d10-11ea-93d6-3211fb9b92a1.png)

The only specific error message I can find about why it's not valid is

> Missing property "build". [1, 1]

but this is only a warning.

**Comment by KittyYeungQ** [comment]
@anpaz-msft Is this something you may know about?

**Comment by cgranade** [comment]
@KittyYeungQ: This is on me.

@marshallsa: I suspect this is because when VS Online launched, it used a slightly different schema for `.devcontainer/devcontainer.json` than VS Code Remote Development. The devcontainer in this repo was originally created for VS Online during that time, and thus may well not be valid for Remote Development. Those two schemas have since been merged, such that we should now be able to support both properly.

**Comment by geduardo** [comment]
Is this solved? @cgranade, @samarsha

**Comment by cgranade** [comment]
Not yet, sorry; had slipped my mind. Let me fix that ASAP.
