### ISSUE TITLE
Tensor product definition

### ISSUE THREAD

**Issue by KittyYeungQ** [MicrosoftDocs/quantum-docs-pr#782]
There's something about our tensor product definition I don't understand:

https://docs.microsoft.com/en-us/quantum/concepts/vectors-and-matrices

The wikipedia page it links to defines tensor product of two vectors to be a multiplication of the first vector and the transpose of the second vector, producing a matrix. But in our case, the tensor products of two vectors still produce a vector. For example: |00>=\begin{bmatrix} 1 \\ 0 \end{bmatrix} \otimes \begin{bmatrix} 1 \\ 0 \end{bmatrix} =\begin{bmatrix} 1 \\ 0 \\0 \\0 \end{bmatrix} 

Why is that?

**Comment by rmshaffer** [comment]
I think the [Kronecker product](https://en.wikipedia.org/wiki/Kronecker_product) page might be a better target for this link. The portion of the 'tensor product' page you're referring to is describing an outer product. [Farther down the page](https://en.wikipedia.org/wiki/Tensor_product#Tensor_product_of_linear_maps) it does discuss the Kronecker product, but to avoid confusion probably this should just link to the page on the Kronecker product.

**Comment by KittyYeungQ** [comment]
That's right. I think we should change the name to Kronecker product and link to the Kronecker product page?

**Comment by rmshaffer** [comment]
Tensor product is the most common name for this when talking about quantum states and operators, so I think it's good that we call it that, but in linear algebra (and thus on these Wikipedia pages, which seem to be linear-algebra-focused) it's more commonly called Kronecker product. The doc page already does mention "the tensor product (or Kronecker product)", but you're right, I think it would be better if this linked to the Kronecker product Wikipedia page, not the tensor product page.

**Comment by cgranade** [comment]
Roughly, the tensor product concatenates the indices of two tensors; since vectors are rank-1 tensors, their tensor product is a rank-2 tensor (matrix). By contrast, a Kronecker product treats its operands as matrices and flattens them back into matrices. In quantum computing, the convention is generally to use the Kronecker product to represent the tensor product by remembering how each matrix index breaks down into indices for each qubit (e.g.: using a tensor network to represent a vector, or how the `dims` property of QuTiP `Qobj` distinguishes between the state of a qu4it and two qubits).

Given that, I don't know that either of the two Wikipedia pages mentioned perfectly covers the way these products are used in quantum computing. It may be best to find another more appropriate resource to link to, especially since the contents of any given Wikipedia page are liable to change with time.
