### ISSUE TITLE
Synchronize named types and their items with the actual Q# types

### ISSUE THREAD

**Issue by tcNickolas** [MicrosoftDocs/quantum-docs-pr#917]
We have [Complex type](https://github.com/microsoft/qsharp-runtime/blob/2151e10c3d09b61be9a1973948568c3394de0b38/src/Simulation/QsharpCore/Math/Types.qs#L14) with items `Real` and `Imag`, and [ComplexPolar type](https://github.com/microsoft/QuantumLibraries/blob/master/Standard/src/Math/Complex.qs#L16) with items `Magnitude` and `Argument`. The types offered as an example on this page look the same, Complex and Polar, but have different item names. This is extremely confusing for the reader, since our API docs doesn't mention the item names of these types ([Complex](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.math.complex), [ComplexPolar](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.math.complexpolar)), and this documentation page is the next most natural place for the learner to see. 

It would be great to use type names and item names that match actual Q# types, or alternatively some completely fictitious types and items that don't resemble any Q# types.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c09f76d3-5d53-f5d3-54e0-a2e31b3e6fd3
* Version Independent ID: 20ac3f86-7520-fe54-8585-8c4b7c44ad4b
* Content: [Types in Q# - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/user-guide/language/types)
* Content Source: [articles/user-guide/language/types.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/user-guide/language/types.md)
* Product: **quantum**
* GitHub Login: @gillenhaalb
* Microsoft Alias: **a-gibec@microsoft.com**

**Comment by jainvasu631** [comment]
We could replace `Complex` with Point2D =` (X: Double, Y: Double)`
a function example could be `Distance(A: Point2D, B:Point2D) : Double`.
Similarly `Polar` is replaced by `Polar2D`. Having similar function implemented on it.

This way the `Complex` and `Polar` can be replaced with `Point2D` and `Polar2D`. This would also avoid the confusion with Complex and ComplexPolar.

**Comment by gillenhaalb** [comment]
@tcNickolas great catch and great point, I completely agree. I think in this case, it'll be best to edit the examples so they align with the actual Q# types (because the text specifically references that). Definitely in agreement regarding completely fictitious names for those sorts of examples in general though. I'll take care of this page.

That does raise another question though---why aren't the API docs indicating the type names (e.g. `Real` and `Imag` in [Complex type](https://github.com/microsoft/qsharp-runtime/blob/2151e10c3d09b61be9a1973948568c3394de0b38/src/Simulation/QsharpCore/Math/Types.qs#L14)) if they are autogenerated? Would there be some instruction in the auto-generation not to include them? Since they can be very useful, it seems like the kind of thing API should absolutely include.

**Comment by cgranade** [comment]
> That does raise another question though---why aren't the API docs indicating the type names (e.g. `Real` and `Imag` in [Complex type](https://github.com/microsoft/qsharp-runtime/blob/2151e10c3d09b61be9a1973948568c3394de0b38/src/Simulation/QsharpCore/Math/Types.qs#L14)) if they are autogenerated? Would there be some instruction in the auto-generation not to include them? Since they can be very useful, it seems like the kind of thing API should absolutely include.

@gillenhaalb: See https://github.com/microsoft/qsharp-compiler/issues/113 for more context. There's an experimental attempt to resolve that has been posted to https://github.com/microsoft/qsharp-runtime/pull/253 for early feedback, but that experiment has not yet been resourced for development into a release-ready tool.
