### ISSUE TITLE
Equation translation submitted from localization team

### ISSUE THREAD

**Issue by KittyYeungQ** [MicrosoftDocs/quantum-docs-pr#981]
Affected Url : https://github.com/MicrosoftDocs/quantum-docs-pr.zh-TW/blob/live/articles/concepts/vectors-and-matrices.md
Issue: Please go to the page and you can see the broken yaml header.
Proposed Solution: Please add “$$v” to the no-loc list.
Ticket URL: iCM 189815823

**Comment by gillenhaalb** [comment]
@KittyYeungQ Similarly here, I"m a little confused by the nature of the issue. It looks like the live page in the docs weathered the storm (i.e. the YAML errors didn't affect the rendered page; observed by going to the live page and Google Translating it back to English), and the problem is isolated to that github view?

I'm all for fixing it regardless, but how would the simple addition of "$$v" do that? 

Another thing that may not related, but seems odd, is that it looks like some of the metadata itself is being affected by the translator (looked at the raw page from other languages too). Is that normal?
