### ISSUE TITLE
Fix namespace casing in API documentation

### ISSUE THREAD

**Issue by viktorveis** [MicrosoftDocs/quantum-docs-pr#991]
API documentation uses lowercase namespaces. For example, https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.math.arccos includes this line:

> Namespace:microsoft.quantum.math

Pasting it to a Q# program as is results in the following error: 

> error QS6104: No namespace with the name "microsoft.quantum.math" exists. 

The actual namespace is **M**icrosoft.**Q**uantum.**M**ath.

Please update documentation, so that it show correct namespace casing and allows pasting a namespace from documentation to code as is.

**Comment by cgranade** [comment]
Thanks for raising this, it looks like this is a fairly severe regression. Oddly, the namespace is correctly formatted in [the underlying YAML sources](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/master/api/qsharp/microsoft.quantum.math.arccos.yml), such that I suspect this may be a regression on the OPS end.

Adding @KittyYeungQ and @geduardo for awareness.

**Comment by gillenhaalb** [comment]
Note that the "See also:" links also get broken by the lowercase change, but oddly it appears to happen at a different time than the namespace change @cgranade pointed out. E.g. for the [AssertQubit operation](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.diagnostics.assertqubit), the [Q# source file](https://github.com/microsoft/qsharp-runtime/blob/master/src/Simulation/QsharpCore/Diagnostics/AssertQubit.qs) is exactly as it's always been, but the [underlying YAML source](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/master/api/qsharp/microsoft.quantum.diagnostics.assertqubit.yml) for the API has the `seeAlso` term already changed to lowercase while the namespace is still properly formatted.

**Comment by geduardo** [comment]
Could it be caused by the migration to DocFX3?

**Comment by cgranade** [comment]
> Could it be caused by the migration to DocFX3?

That's possible, yeah. It'd be surprising to me that the meaning of the schema used to generate doc HTML pages from YAML files changed that drastically between the two, but it would explain what we're seeing here.

**Comment by cgranade** [comment]
As a side note, one possible path would be to take control of the Q# → API documentation pipeline by directly generating Markdown files from within the Q# compiler and runtime toolchain (https://github.com/microsoft/qsharp-runtime/pull/253).

**Comment by geduardo** [comment]
I've been doing some experiments here (https://github.com/MicrosoftDocs/quantum-docs-pr/pull/999) and going back to DocFX v2 makes the namespaces to look ok again (although some odd warnings appear). Anyways, this seems to confirm my suspicion: something changed in the migration to DocFX3 that caused this issue.

**Comment by cgranade** [comment]
> I've been doing some experiments here (#999) and going back to DocFX v2 makes the namespaces to look ok again (although some odd warnings appear). Anyways, this seems to confirm my suspicion: something changed in the migration to DocFX3 that caused this issue.

Well, crap, that isn't good. Thanks for confirming that; maybe it would be good, then, to accelerate work on https://github.com/microsoft/qsharp-runtime/pull/253 so that we can phase out the YAML files that we don't control templates for.

**Comment by geduardo** [comment]
Sure, I'd love to help with that but my C# skills are not good enough yet (I'm learning this summer tho!). We could try to go back to DocFX v2 until the Markdown generation tool is ready. Maybe we should check with the OPS team first.

**Comment by KittyYeungQ** [comment]
Docs team identified the root cause: @bradben is this something you could fix or may need help from @cgranade @bettinaheim's team? 

"We've noticed that the NameSpace's uid were declared with lower-case, referenced with upper-case. Since uid is case-sensitive, this result into xref-not-found and lower-cased uid got displayed in stead of name.
In docfx-v2, template holds the logic to fix this(turn upper-case to lower-case). But due to v3 xref behavior change, the fix won't work.
 
An easy approach would be changing the uid reference to lower-case, and the result will be correct. This approach also eliminate the hacky fix in template.
 e.g. Microsoft.Quantum.Math => microsoft.quantum.math
 
more Details in AB#[288357](https://dev.azure.com/ceapex/Engineering/_workitems/edit/288357)

v2: yml -> verify uid(uid-not-found v2 report) -> jint(uid lower cased) -> mustache -> resolve uid again(resolved)
v3: yml -> resolve uid(xref-not-found v3 report) -> jint -> mustache

uid declaration: microsoft.quantum.math
uid reference: Microsoft.Quantum.Math

the yml files were machine generated, and hence it would be great if this fix happens during generation.

### YamlMime:QSharpType
# This file is automatically generated.
# Please do not modify this file manually, or your changes may be lost when
# documentation is rebuilt.
uid: microsoft.quantum.math.arccos
name: ArcCos
type: function
namespace: Microsoft.Quantum.Math <= here need to be changed

NameSpace reference need to be lower-cased "Microsoft.Quantum.Math => microsoft.quantum.math"."

**Comment by rmshaffer** [comment]
@KittyYeungQ, will that approach end up rendering the casing correctly in the documentation, e.g., as `Microsoft.Quantum.Math`?

**Comment by herohua** [comment]
@mingwli Can you comment on @rmshaffer 's question above?

**Comment by mingwli** [comment]
@rmshaffer 
```
### YamlMime:QSharpType
# This file is automatically generated.
# Please do not modify this file manually, or your changes may be lost when
# documentation is rebuilt.
uid: microsoft.quantum.math.arccos
name: ArcCos
type: function
namespace: Microsoft.Quantum.Math <= here need to be changed
```

NameSpace reference need to be lower-cased [Microsoft.Quantum.Math](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/api/qsharp/microsoft.quantum.math.arccos.yml#L9) => microsoft.quantum.math

**Comment by KittyYeungQ** [comment]
Hi @mingwli would you mind helping us understand, so the namespace initials should never have been upper-cased in the yaml file of the live view? We intended to have live view have upper case. Is it no longer possible?

**Comment by mingwli** [comment]
@KittyYeungQ  The view will be **Upper Case** eventually.

It's a bit complicated to explain how it works.
The namespace is declared with `uid` [microsoft.quantum.math](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/mingwli%2Fnamespace-fix/api/qsharp/Microsoft.Quantum.Math.yml#L6-L7). 
And after this, this `uid` can be used within this repo to reference the namespace e.g. [`namespace: Microsoft.Quantum.Math`](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/mingwli%2Fnamespace-fix/api/qsharp/microsoft.quantum.math.abscomplex.yml#L9). And since the `uid` is case-sensitive, it need to use the right case(lower) to reference.
The final displayed text will be the namespace's [Name](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/mingwli%2Fnamespace-fix/api/qsharp/Microsoft.Quantum.Math.yml#L7) property, which has the correct case.

I've created a branch to demo this #1030, sample built [page](https://review.docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.math.abscomplex?branch=pr-en-us-1030)
![image](https://user-images.githubusercontent.com/42199316/91555653-fe8e6380-e963-11ea-9ca6-b6d0ad50d731.png)

cc @herohua

**Comment by KittyYeungQ** [comment]
https://github.com/microsoft/qsharp-compiler/issues/596
